version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: AsCaEdGaMiEcoExT2018
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 666:8080